baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "MagusLu's Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

[params]
  # FixIt 主题版本
  version = "0.2.14"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
    pre = "<i class='fa-solid fa-archive fa-fw fa-sm'></i>"
    # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
    post = ""
    name = "所有文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时，将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "categories"
    pre = "<i class='fa-solid fa-th fa-fw fa-sm'></i>"
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = "<i class='fa-solid fa-tags fa-fw fa-sm'></i>"
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
	identifier = "about"
	pre = "<i class='fa-solid fa-info-circle fa-fw fa-sm'></i>"
	post = ""
	name = "关于"
	url = "/about/"
	title = ""
	weight = 4
  [[menu.main]]
	identifier = "github"
	pre = "<i class='fa-brands fa-github fa-fw'></i>"
	post = ""
	name = ""
	url = "https://github.com/Lruihao/FixIt"
	title = "GitHub"
	weight = 5
	[menu.main.params]
	  class = "d-none-desktop text-center"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/Lruihao/FixIt/issues/43)
    noClasses = false
